### PR TITLE
Initial toolkit with Matrix addition added

### LINKED ISSUE #1: Create Toolkit
Linked to https://github.com/BHoM/BHoM_Engine/issues/562

Create initial design of the toolkit to your ideas @EKAdebo - you have free reign 😄

### LINKED ISSUE #562: Global: Do we need a Maths_Engine?
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #1 
Closes https://github.com/BHoM/BHoM_Engine/issues/562

Creation of the maths toolkit!
Happy Pi day :)

### Additional comments

Makes a start for Matrix calculations within BHoM framework, but needs further effort.

### CODE REVIEW

**Comment by EKAdebo** [comment]
Hi! @BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot fix copyright headers ref. 11998247752

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
Hi again old friend @BHoMBot fix copyright headers ref. 11998247752

**Comment by EKAdebo** [comment]
@BHoMBot fix copyright headers ref. 11998247752

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check unit-tests

**Review by FraserGreenroyd — APPROVED** [review]
Looks good, unit tests look good, @alelom will be happy with someone else using some NUnit framework I'm sure 😉 

This is a fun first step into the foray into Maths related operations in the BHoM as described in https://github.com/BHoM/BHoM_Engine/issues/562 - hopefully people can build on this and when we're happy, look to migrate up to the core of BHoM and BHoM_Engine.

Great work @EKAdebo 😄

**Pull request merged**
